### ISSUE TITLE
how much RAM needed

### ISSUE THREAD

**Issue by trung6** [Lynn1/llama3-on-2GPUs#1]
Thank you for your code!

I got the following error when running it. `RuntimeError: [enforce fail at alloc_cpu.cpp:117] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 117440512 bytes. Error code 12 (Cannot allocate memory)`

So, I wonder how much memory you needed to run the script?

**Comment by Lynn1** [comment]
If you don't have enough memory, I think you can increase the virtual memory by setting up the swap file on your linux system.

**Comment by trung6** [comment]
Thanks! In my case, what I did was instead of processing all 8 weight files at once, I processed 4 each time.
